image: "gagara/logstash-oss-arm64"
imageTag: "7.6.2"

logstashConfig: 
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline

logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
          match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
      date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
      }
      geoip {
          source => "clientip"
        }
      }
      output {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
      }
     }

# extraPorts:
#   - name: beats
#     port: 5044
#     protocol: TCP
          
service:
  type: ClusterIP
  ports:
    - name: beats
      protocol: TCP
      port: 5044
      targetPort: 5044
